const instrumentsList = [
    'Piano',
    'Guitar',
    'Violin',
    'Drums',
    'Flute',
    'Saxophone',
    'Trumpet',
    'Cello',
    'Clarinet',
    'Harp',
    'Bass Guitar',
    'Double Bass',
    'Oboe',
    'Trombone',
    'Tuba',
    'Mandolin',
    'Banjo',
    'Harmonica',
    'Accordion',
    'Ukulele',
    'Bagpipes',
    'Sitar',
    'Xylophone',
    'Marimba',
    'Timpani',
    'Bongo Drums',
    'Conga',
    'Didgeridoo',
    'Bassoon',
    'Piccolo',
    'French Horn',
    'English Horn',
    'Tabla',
    'Theremin'
  ];

export default instrumentsList;